all: test_nrpc.proto
	#goneat create -protodir=. -protofile=test_nrpc.proto -protocol=nrpc -v -assetdir=/Users/zhangjie/.goneat/asset/
	goneat create -protodir=. -protofile=test_nrpc.proto -protocol=nrpc

.PHONY: clean

clean:
	rm -rf test_nrpc
