// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gorpc.proto

package gorpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PkgHeader request/response统一包头
//
// 二进制编码协议：
// | STX | PKG LENGTH | Request/Response BODY | ETX |
// 0     1            5                       ~    ~+1
//
// In Request, tracing `traceContext` is stored in map `meta`.
type Request struct {
	Seqno                *uint64           `protobuf:"varint,1,opt,name=seqno" json:"seqno,omitempty"`
	Appid                *string           `protobuf:"bytes,2,opt,name=appid" json:"appid,omitempty"`
	Userid               *string           `protobuf:"bytes,3,opt,name=userid" json:"userid,omitempty"`
	Userkey              *string           `protobuf:"bytes,4,opt,name=userkey" json:"userkey,omitempty"`
	Version              *uint32           `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Body                 []byte            `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,7,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e28fa15f1ee6267d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSeqno() uint64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *Request) GetAppid() string {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return ""
}

func (m *Request) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *Request) GetUserkey() string {
	if m != nil && m.Userkey != nil {
		return *m.Userkey
	}
	return ""
}

func (m *Request) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// In Response, frame only return `err_msg` , why? `err_code` is easy to conflide
// with user developing, so here `err_code` can only be set by business logic.
type Response struct {
	Seqno                *uint64  `protobuf:"varint,1,opt,name=seqno" json:"seqno,omitempty"`
	ErrCode              *uint32  `protobuf:"varint,2,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,3,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e28fa15f1ee6267d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSeqno() uint64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *Response) GetErrCode() uint32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "gorpc.Request")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Request.MetaEntry")
	proto.RegisterType((*Response)(nil), "gorpc.Response")
}

func init() { proto.RegisterFile("gorpc.proto", fileDescriptor_e28fa15f1ee6267d) }

var fileDescriptor_e28fa15f1ee6267d = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x26, 0x69, 0xda, 0x2b, 0x95, 0x90, 0x85, 0xc0, 0x30, 0x59, 0x9d, 0x3c, 0xa0,
	0x0c, 0x2c, 0x20, 0x56, 0xc4, 0xd8, 0xc5, 0x2f, 0x50, 0x85, 0xfa, 0x14, 0x22, 0x68, 0xec, 0x9e,
	0x9d, 0x4a, 0x79, 0x77, 0x06, 0x64, 0xa7, 0x29, 0x13, 0xdb, 0xff, 0xfd, 0x97, 0xe8, 0xee, 0x33,
	0xac, 0x1a, 0x4b, 0x6e, 0x5f, 0x39, 0xb2, 0xc1, 0xf2, 0x22, 0xc1, 0xe6, 0x87, 0x41, 0xa9, 0xf1,
	0xd8, 0xa3, 0x0f, 0xfc, 0x06, 0x0a, 0x8f, 0xc7, 0xce, 0x0a, 0x26, 0x99, 0xca, 0xf5, 0x08, 0xb1,
	0xad, 0x9d, 0x6b, 0x8d, 0x98, 0x49, 0xa6, 0x96, 0x7a, 0x04, 0x7e, 0x0b, 0xf3, 0xde, 0x23, 0xb5,
	0x46, 0x64, 0xa9, 0x3e, 0x13, 0x17, 0x50, 0xc6, 0xf4, 0x85, 0x83, 0xc8, 0xd3, 0x60, 0xc2, 0x38,
	0x39, 0x21, 0xf9, 0xd6, 0x76, 0xa2, 0x90, 0x4c, 0xad, 0xf5, 0x84, 0x9c, 0x43, 0xfe, 0x61, 0xcd,
	0x20, 0xe6, 0x92, 0xa9, 0x2b, 0x9d, 0x32, 0x7f, 0x84, 0xfc, 0x80, 0xa1, 0x16, 0xa5, 0xcc, 0xd4,
	0xea, 0x49, 0x54, 0xe3, 0xe9, 0xe7, 0x4b, 0xab, 0x2d, 0x86, 0xfa, 0xbd, 0x0b, 0x34, 0xe8, 0xf4,
	0xd5, 0xc3, 0x33, 0x2c, 0x2f, 0x15, 0xbf, 0x86, 0x2c, 0xae, 0x67, 0x69, 0x7d, 0x8c, 0x51, 0xe1,
	0x54, 0x7f, 0xf7, 0x38, 0x29, 0x24, 0x78, 0x9d, 0xbd, 0xb0, 0xcd, 0x27, 0x2c, 0x34, 0x7a, 0x67,
	0x3b, 0x8f, 0xff, 0xe8, 0xdf, 0xc3, 0x02, 0x89, 0x76, 0x7b, 0x6b, 0xc6, 0xdf, 0xd7, 0xba, 0x44,
	0xa2, 0x37, 0x6b, 0x90, 0xdf, 0x41, 0x8c, 0xbb, 0x83, 0x6f, 0xa6, 0x47, 0x40, 0xa2, 0xad, 0x6f,
	0x2e, 0x42, 0xf9, 0x9f, 0xd0, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xfc, 0xbf, 0x72, 0x7d,
	0x01, 0x00, 0x00,
}
